#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

ln -sf $OPENSHIFT_DATA_DIR/wp-config.php $OPENSHIFT_REPO_DIR/php/wp-config.php
